### ISSUE TITLE
Fitbit Battery Level, Hours/Minutes since last sync 

### ISSUE THREAD

**Issue by NickChristensen** [ctaloi/Fitboard#2]
I'd love a widget that showed me info about my Ffitbit itself, specifically battery level and  time since last sync. It looks like you're already pulling that from the API, would it be tough to add a widget for it?

Sorry, should have just asked here in the first place.

**Comment by ctaloi** [comment]
Thanks Nick - Working on adding this.

**Comment by ctaloi** [comment]
@NickChristensen Any thoughts on other useful data points to display in the widget?  Right now I have:
- Battery
- Last Sync

Wondering what else might be useful

**Comment by ctaloi** [comment]
Will close when I push the new code

**Comment by ctaloi** [comment]
pushed code to production
